
try:
  print("try catch training")
# case of error
except:
  print("Something went wrong")
# case of no error
else:
  print("no exeption found")
# will be done anyway
finally:
  print("The 'try except' is finished")





